variable "vpc_name" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "database_subnets" {}
variable "Business_Divison" {}
#variable "azs" {}
variable "env" {}
variable "vpc_cidr_block" {}
variable "vpc_create_database_subnets" {}
variable "vpc_create_database_subnet_route_table" {}
variable "vpc_enable_nat_gateway" {}
variable "vpc_single_nat_gateway" {}
variable "github_token" {}
variable "github_repo_name" {}
